const FAMOUS_STREET_NAMES = new Set([
  "avenue des champs-élysées",
  "avenue de l'opéra",
  "avenue foch",
  "avenue montaigne",
  "avenue de la grande armée",
  "avenue victor hugo",
  "avenue kléber",
  "avenue george v",
  "avenue marceau",
  "avenue d'iéna",
  "avenue du président wilson",
  "avenue de wagram",
  "avenue mac-mahon",
  "avenue carnot",
  "avenue niel",
  "avenue de la république",
  "avenue parmentier",
  "avenue ledru-rollin",
  "avenue daumesnil",
  "avenue de saint-mandé",
  "avenue de la division leclerc",
  "avenue rené coty",
  "avenue du général leclerc",
  "avenue jean moulin",
  "avenue du maine",
  "avenue de breteuil",
  "avenue de saxe",
  "avenue de la motte-picquet",
  "avenue de tourville",
  "avenue de suffren",
  "avenue de la bourdonnais",
  "avenue bosquet",
  "avenue rapp",
  "avenue de lowendal",
  "avenue de villars",
  "boulevard saint-germain",
  "boulevard saint-michel",
  "boulevard haussmann",
  "boulevard des capucines",
  "boulevard des italiens",
  "boulevard de la madeleine",
  "boulevard montmartre",
  "boulevard poissonnière",
  "boulevard de bonne nouvelle",
  "boulevard saint-denis",
  "boulevard saint-martin",
  "boulevard du temple",
  "boulevard des filles du calvaire",
  "boulevard beaumarchais",
  "boulevard de sébastopol",
  "boulevard de strasbourg",
  "boulevard de magenta",
  "boulevard barbès",
  "boulevard de la chapelle",
  "boulevard de rochechouart",
  "boulevard de clichy",
  "boulevard de courcelles",
  "boulevard malesherbes",
  "boulevard pereire",
  "boulevard gouvion-saint-cyr",
  "boulevard lannes",
  "boulevard suchet",
  "boulevard murat",
  "boulevard exelmans",
  "boulevard victor",
  "boulevard lefebvre",
  "boulevard brune",
  "boulevard jourdan",
  "boulevard kellermann",
  "boulevard masséna",
  "boulevard poniatowski",
  "boulevard soult",
  "boulevard davout",
  "boulevard mortier",
  "boulevard sérurier",
  "boulevard macdonald",
  "boulevard ney",
  "boulevard bessières",
  "boulevard berthier",
  "boulevard de l'hôpital",
  "boulevard de la gare",
  "boulevard vincent auriol",
  "boulevard d'italie",
  "boulevard auguste blanqui",
  "boulevard saint-jacques",
  "boulevard de port-royal",
  "boulevard du montparnasse",
  "boulevard des invalides",
  "boulevard raspail",
  "boulevard richard-lenoir",
  "boulevard voltaire",
  "boulevard diderot",
  "rue de rivoli",
  "rue saint-honoré",
  "rue du faubourg saint-honoré",
  "rue de la paix",
  "rue royale",
  "rue de passy",
  "rue de rennes",
  "rue de vaugirard",
  "rue de l'université",
  "rue saint-dominique",
  "rue de grenelle",
  "rue de varenne",
  "rue du bac",
  "rue des saints-pères",
  "rue de seine",
  "rue mazarine",
  "rue de buci",
  "rue saint-andré des arts",
  "rue mouffetard",
  "rue soufflot",
  "rue des écoles",
  "rue saint-jacques",
  "rue de la huchette",
  "rue de la harpe",
  "rue saint-denis",
  "rue saint-martin",
  "rue du temple",
  "rue vieille du temple",
  "rue des rosiers",
  "rue des francs bourgeois",
  "rue de lappe",
  "rue de la roquette",
  "rue du faubourg saint-antoine",
  "rue de charenton",
  "rue oberkampf",
  "rue de belleville",
  "rue de ménilmontant",
  "rue des martyrs",
  "rue lepic",
  "rue norvins",
  "rue saint-rustique",
  "rue de l'abreuvoir",
  "rue caulaincourt",
  "rue de rome",
  "rue la fayette",
  "rue de châteaudun",
  "place de la concorde",
  "place charles de gaulle",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "place de l'opéra",
  "place vendôme",
  "place des vosges",
  "place du tertre",
  "place de la madeleine",
  "place d'italie",
  "square du vert-galant",
]);

const MAIN_STREET_NAMES = new Set([
  "avenue des champs-élysées",
  "avenue de l'opéra",
  "avenue foch",
  "avenue montaigne",
  "avenue de la grande armée",
  "avenue victor hugo",
  "avenue kléber",
  "avenue george v",
  "avenue marceau",
  "avenue d'iéna",
  "avenue du président wilson",
  "avenue de wagram",
  "avenue mac-mahon",
  "avenue carnot",
  "avenue niel",
  "avenue de la république",
  "avenue parmentier",
  "avenue ledru-rollin",
  "avenue daumesnil",
  "avenue de saint-mandé",
  "avenue de la division leclerc",
  "avenue rené coty",
  "avenue du général leclerc",
  "avenue jean moulin",
  "avenue du maine",
  "avenue de breteuil",
  "avenue de saxe",
  "avenue de la motte-picquet",
  "avenue de tourville",
  "avenue de suffren",
  "avenue de la bourdonnais",
  "avenue bosquet",
  "avenue rapp",
  "avenue de lowendal",
  "avenue de villars",
  "avenue de saint-ouen",
  "avenue de clichy",
  "avenue de la porte de clichy",
  "avenue de la porte de saint-ouen",
  "avenue de la porte d'asnières",
  "avenue de villiers",
  "avenue de la porte de champerret",
  "avenue de la porte des ternes",
  "avenue des ternes",
  "avenue de la porte de neuilly",
  "avenue de la porte de la muette",
  "avenue de la porte d'auteuil",
  "avenue de versailles",
  "avenue de la porte de saint-cloud",
  "avenue d'eylau",
  "avenue raymond poincaré",
  "avenue bugeaud",
  "avenue d'iéna",
  "avenue albert de mun",
  "avenue de new york",
  "avenue de malakoff",
  "avenue de la porte de sèvres",
  "avenue émile zola",
  "avenue félix faure",
  "avenue de la porte de versailles",
  "avenue de la porte de plaisance",
  "avenue de la porte de brancion",
  "avenue de la porte de vanves",
  "avenue de la porte de châtillon",
  "avenue de la porte d'orléans",
  "avenue de la porte d'italie",
  "avenue de la porte de choisy",
  "avenue de la porte d'ivry",
  "avenue des gobelins",
  "avenue de la porte de vitry",
  "avenue de la porte de france",
  "avenue de la porte de charenton",
  "avenue de la porte de vincennes",
  "avenue de la porte de montreuil",
  "avenue de la porte de bagnolet",
  "avenue de la porte des lilas",
  "avenue de la porte du pré-saint-gervais",
  "avenue de la porte de pantin",
  "avenue de la porte de la villette",
  "avenue de la porte d'aubervilliers",
  "avenue de la porte de la chapelle",
  "avenue de la porte des poissonniers",
  "boulevard saint-germain",
  "boulevard saint-michel",
  "boulevard haussmann",
  "boulevard des capucines",
  "boulevard des italiens",
  "boulevard de la madeleine",
  "boulevard montmartre",
  "boulevard poissonière",
  "boulevard bonne nouvelle",
  "boulevard saint-denis",
  "boulevard saint-martin",
  "boulevard du temple",
  "boulevard des filles du calvaire",
  "boulevard beaumarchais",
  "boulevard de sébastopol",
  "boulevard de strasbourg",
  "boulevard de magenta",
  "boulevard barbès",
  "boulevard de la chapelle",
  "boulevard de rochechouart",
  "boulevard de clichy",
  "boulevard de courcelles",
  "boulevard malesherbes",
  "boulevard pereire",
  "boulevard gouvion-saint-cyr",
  "boulevard lannes",
  "boulevard suchet",
  "boulevard murat",
  "boulevard exelmans",
  "boulevard victor",
  "boulevard lefebvre",
  "boulevard brune",
  "boulevard jourdan",
  "boulevard kellermann",
  "boulevard masséna",
  "boulevard poniatowski",
  "boulevard soult",
  "boulevard davout",
  "boulevard mortier",
  "boulevard sérurier",
  "boulevard macdonald",
  "boulevard ney",
  "boulevard bessières",
  "boulevard berthier",
  "boulevard de l'hôpital",
  "boulevard de la gare",
  "boulevard vincent auriol",
  "boulevard d'italie",
  "boulevard auguste blanqui",
  "boulevard saint-jacques",
  "boulevard de de port-royal",
  "boulevard du montparnasse",
  "boulevard des invalides",
  "boulevard raspail",
  "boulevard richard-lenoir",
  "boulevard voltaire",
  "boulevard diderot",
  "boulevard de la bastille",
  "boulevard de bourdon",
  "boulevard de la contrescarpe",
  "boulevard henri iv",
  "boulevard morland",
  "boulevard de l'arsenal",
  "boulevard de la zone",
  "boulevard de belleville",
  "boulevard de ménilmontant",
  "boulevard de charonne",
  "boulevard de picpus",
  "boulevard de bercy",
  "boulevard de la guyane",
  "boulevard de l'algérie",
  "boulevard de l'indochine",
  "boulevard d'algérie",
  "boulevard de reims",
  "boulevard pershing",
  "rue de rivoli",
  "rue saint-honoré",
  "rue du faubourg saint-honoré",
  "rue de la paix",
  "rue royale",
  "rue de passy",
  "rue de rennes",
  "rue de vaugirard",
  "rue de l'université",
  "rue saint-dominique",
  "rue de grenelle",
  "rue de varenne",
  "rue du bac",
  "rue des saints-pères",
  "rue de seine",
  "rue mazarine",
  "rue de buci",
  "rue saint-andré des arts",
  "rue mouffetard",
  "rue soufflot",
  "rue des écoles",
  "rue saint-jacques",
  "rue de la huchette",
  "rue de la harpe",
  "rue saint-denis",
  "rue saint-martin",
  "rue du temple",
  "rue vieille du temple",
  "rue des rosiers",
  "rue des francs-bourgeois",
  "rue de lappe",
  "rue de la roquette",
  "rue du faubourg saint-antoine",
  "rue de charenton",
  "rue oberkampf",
  "rue de belleville",
  "rue de ménilmontant",
  "rue des martyrs",
  "rue lepic",
  "rue norvins",
  "rue saint-rustique",
  "rue de l'abreuvoir",
  "rue caulaincourt",
  "rue de rome",
  "rue de lafayette",
  "rue de châteaudun",
  "rue de la pompe",
  "rue de longchamp",
  "rue lauriston",
  "rue de courcelles",
  "rue de monceau",
  "rue de lisbonne",
  "rue de madrid",
  "rue de constantinople",
  "rue de londres",
  "rue d'amsterdam",
  "rue de clichy",
  "rue blanche",
  "rue de la chaussée d'antin",
  "rue de provence",
  "rue de la victoire",
  "rue de maubeuge",
  "rue de dunkerque",
  "rue du faubourg saint-denis",
  "rue du faubourg saint-martin",
  "rue du faubourg du temple",
  "rue de la fontaine au roi",
  "rue jean-pierre timbaud",
  "rue de la roquette",
  "rue de charonne",
  "rue de bagnolet",
  "rue d'avron",
  "rue de lagny",
  "rue de picpus",
  "rue de reuilly",
  "rue de bercy",
  "rue de charenton",
  "rue de lyon",
  "rue de l'arsenal",
  "rue saint-antoine",
  "rue de la verrerie",
  "rue du roi de sicile",
  "rue de rivoli",
  "rue françois miron",
  "rue des barres",
  "rue de l'hôtel de ville",
  "rue de la harpe",
  "rue de la huchette",
  "rue galande",
  "rue de la parcheminerie",
  "rue saint-séverin",
  "rue de la montagne sainte-geneviève",
  "rue descartes",
  "rue monge",
  "rue claude bernard",
  "rue d'ulm",
  "rue gay-lussac",
  "rue de l'abbé de l'épée",
  "rue d'assas",
  "rue de notre-dame des champs",
  "rue de chevreuse",
  "rue de la grande chaumière",
  "rue de fleurus",
  "rue de bonaparte",
  "rue jacob",
  "rue du cherche-midi",
  "rue du dragon",
  "rue de l'arrivée",
  "rue du départ",
  "rue de la gaîté",
  "rue de l'ouest",
  "rue raymond losserand",
  "rue didot",
  "rue d'alésia",
  "rue de la tombe-issoire",
  "rue du faubourg saint-jacques",
  "rue de la santé",
  "rue de la glacière",
  "rue de tolbiac",
  "rue bobillot",
  "rue de patay",
  "rue de domrémy",
  "rue du chevaleret",
  "rue jeanne d'arc",
  "rue de la convention",
  "rue de lourmel",
  "rue de la croix nivert",
  "rue lecourbe",
  "rue de l'abbé groult",
  "rue de commerce",
  "rue du théâtre",
  "rue de l'église",
  "rue saint-charles",
  "rue de l'amiral roussin",
  "rue de javel",
  "rue balard",
  "rue de la fédération",
  "rue de presles",
  "rue de buenos ayres",
  "rue de l'exposition",
  "rue augereau",
  "rue de l'université",
  "rue de grenelle",
  "rue saint-dominique",
  "rue de bourgogne",
  "rue de bellechasse",
  "rue de solférino",
  "rue de poitiers",
  "rue de lille",
  "rue de verneuil",
  "rue de beaune",
  "place de la concorde",
  "place charles de gaulle (étoile)",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "place de l'opéra",
  "place vendôme",
  "place des vosges",
  "place du tertre",
  "place de la madeleine",
  "place d'italie",
  "square du vert-galant",
  "place denfert-rochereau",
  "place de clichy",
  "place de la catalogne",
  "place de l'hôtel de ville",
  "place du châtelet",
  "place saint-michel",
  "place de la sorbonne",
  "place du panthéon",
  "place de la contrescarpe",
  "place monge",
  "place d'italie",
  "place de la bataille de stalingrad",
  "place du colonel fabien",
  "place de la bourse",
  "place des victoires",
  "place du palais royal",
  "place franz liszt",
  "place de l'europe",
  "place de rio de janeiro",
  "place de narvik",
  "place de l'alma",
  "place du trocadéro et du 11 novembre",
  "place de la porte de saint-cloud",
  "place d'asnières",
  "place de la porte de champerret",
  "place de la porte des ternes",
  "place de la porte de maillot",
  "place de la porte de passy",
  "place de la porte d'auteuil",
  "place de la porte de versailles",
  "place de la porte de vanves",
  "place de la porte d'orléans",
  "place de la porte d'italie",
  "place de la porte de vincennes",
  "place de la porte de pantin",
  "place de la porte de la villette",
  "place de la porte de la chapelle",
  "square des batignolles",
  "square édouard vii",
  "square de montholon",
  "square de la roquette",
  "square rené le gall",
  "square boucicaut",
  "quai des orfèvres",
  "quai de la mégisserie",
  "quai de l'hôtel de ville",
  "quai de la tournelle",
  "quai de l'horloge",
  "quai voltaire",
  "quai d'orsay",
  "quai de branly",
  "quai de grenelle",
  "quai andré citroën",
]);

const MONUMENT_NAMES = new Set([
  "tour eiffel",
  "musée du louvre",
  "cathédrale notre-dame de paris",
  "arc de triomphe",
  "sacré-cœur",
  "panthéon",
  "opéra garnier",
  "hôtel de ville",
  "place de la concorde",
  "place des vosges",
  "jardin du luxembourg",
  "jardin des tuileries",
  "centre pompidou",
  "musée d'orsay",
  "invalides",
  "grand palais",
  "petit palais",
  "palais de chaillot",
  "palais royal",
  "conciergerie",
  "sainte-chapelle",
  "cimetière du père-lachaise",
  "tour montparnasse",
  "bibliothèque nationale de france",
  "institut du monde arabe",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "canal saint-martin",
  "moulin rouge",
  "galeries lafayette",
  "la samaritaine",
  "pont alexandre iii",
  "pont neuf",
  "pont des arts",
  "pont de bir-hakeim",
  "parc des buttes-chaumont",
  "parc monceau",
  "bois de boulogne",
  "bois de vincennes",
]);

const ARRONDISSEMENT_PAR_QUARTIER = Object.fromEntries(
  Array.from({ length: 20 }, (_, index) => {
    const number = index + 1;
    const label = number === 1 ? "1er arrondissement" : `${number}e arrondissement`;
    return [label, number === 1 ? "1er" : `${number}e`];
  }),
);

if (typeof module !== "undefined" && module.exports) {
  module.exports = { FAMOUS_STREET_NAMES, MAIN_STREET_NAMES, MONUMENT_NAMES, ARRONDISSEMENT_PAR_QUARTIER };
}
