const FAMOUS_STREET_NAMES = new Set([
  "avenue des champs-élysées",
  "avenue de l'opéra",
  "avenue foch",
  "avenue montaigne",
  "avenue de la grande armée",
  "avenue victor hugo",
  "avenue kléber",
  "avenue george v",
  "avenue marceau",
  "avenue d'iéna",
  "avenue du président wilson",
  "avenue de wagram",
  "avenue mac-mahon",
  "avenue carnot",
  "avenue niel",
  "avenue de la république",
  "avenue parmentier",
  "avenue ledru-rollin",
  "avenue daumesnil",
  "avenue de saint-mandé",
  "avenue de la division leclerc",
  "avenue rené coty",
  "avenue du général leclerc",
  "avenue jean moulin",
  "avenue du maine",
  "avenue de breteuil",
  "avenue de saxe",
  "avenue de la motte-picquet",
  "avenue de tourville",
  "avenue de suffren",
  "avenue de la bourdonnais",
  "avenue bosquet",
  "avenue rapp",
  "avenue de lowendal",
  "avenue de villars",
  "boulevard saint-germain",
  "boulevard saint-michel",
  "boulevard haussmann",
  "boulevard des capucines",
  "boulevard des italiens",
  "boulevard de la madeleine",
  "boulevard montmartre",
  "boulevard poissonnière",
  "boulevard de bonne nouvelle",
  "boulevard saint-denis",
  "boulevard saint-martin",
  "boulevard du temple",
  "boulevard des filles du calvaire",
  "boulevard beaumarchais",
  "boulevard de sébastopol",
  "boulevard de strasbourg",
  "boulevard de magenta",
  "boulevard barbès",
  "boulevard de la chapelle",
  "boulevard de rochechouart",
  "boulevard de clichy",
  "boulevard de courcelles",
  "boulevard malesherbes",
  "boulevard pereire",
  "boulevard gouvion-saint-cyr",
  "boulevard lannes",
  "boulevard suchet",
  "boulevard murat",
  "boulevard exelmans",
  "boulevard victor",
  "boulevard lefebvre",
  "boulevard brune",
  "boulevard jourdan",
  "boulevard kellermann",
  "boulevard masséna",
  "boulevard poniatowski",
  "boulevard soult",
  "boulevard davout",
  "boulevard mortier",
  "boulevard sérurier",
  "boulevard macdonald",
  "boulevard ney",
  "boulevard bessières",
  "boulevard berthier",
  "boulevard de l'hôpital",
  "boulevard de la gare",
  "boulevard vincent auriol",
  "boulevard d'italie",
  "boulevard auguste blanqui",
  "boulevard saint-jacques",
  "boulevard de port-royal",
  "boulevard du montparnasse",
  "boulevard des invalides",
  "boulevard raspail",
  "boulevard richard-lenoir",
  "boulevard voltaire",
  "boulevard diderot",
  "rue de rivoli",
  "rue saint-honoré",
  "rue du faubourg saint-honoré",
  "rue de la paix",
  "rue royale",
  "rue de passy",
  "rue de rennes",
  "rue de vaugirard",
  "rue de l'université",
  "rue saint-dominique",
  "rue de grenelle",
  "rue de varenne",
  "rue du bac",
  "rue des saints-pères",
  "rue de seine",
  "rue mazarine",
  "rue de buci",
  "rue saint-andré des arts",
  "rue mouffetard",
  "rue soufflot",
  "rue des écoles",
  "rue saint-jacques",
  "rue de la huchette",
  "rue de la harpe",
  "rue saint-denis",
  "rue saint-martin",
  "rue du temple",
  "rue vieille du temple",
  "rue des rosiers",
  "rue des francs bourgeois",
  "rue de lappe",
  "rue de la roquette",
  "rue du faubourg saint-antoine",
  "rue de charenton",
  "rue oberkampf",
  "rue de belleville",
  "rue de ménilmontant",
  "rue des martyrs",
  "rue lepic",
  "rue norvins",
  "rue saint-rustique",
  "rue de l'abreuvoir",
  "rue caulaincourt",
  "rue de rome",
  "rue la fayette",
  "rue de châteaudun",
  "place de la concorde",
  "place charles de gaulle",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "place de l'opéra",
  "place vendôme",
  "place des vosges",
  "place du tertre",
  "place de la madeleine",
  "place d'italie",
  "square du vert-galant",
]);

const MAIN_STREET_NAMES = new Set([
  ...FAMOUS_STREET_NAMES,
  "avenue de flandre",
  "avenue corentin cariou",
  "avenue de la porte de la villette",
  "avenue de la porte de clichy",
  "avenue de la porte d'asnières",
  "avenue de la porte maillot",
  "avenue de la porte d'auteuil",
  "avenue de versailles",
  "avenue émile zola",
  "avenue félix faure",
  "avenue du général leclerc",
  "avenue denfert-rochereau",
  "avenue des ternes",
  "avenue mac-mahon",
  "avenue niel",
  "avenue de friedland",
  "avenue hoche",
  "avenue marceau",
  "avenue pierre ier de serbie",
  "avenue bosquet",
  "avenue rapp",
  "avenue lowendal",
  "avenue de ségur",
  "avenue de villiers",
  "avenue de saint-mandé",
  "avenue de la république",
  "avenue gambetta",
  "avenue philippe auguste",
  "avenue de clichy",
  "avenue trudaine",
  "avenue secrétan",
  "avenue mathurin moreau",
  "avenue de laumière",
  "avenue de france",
  "avenue pierre mendès france",
  "avenue des champs-élysées",
  "boulevard périphérique",
  "boulevard lannes",
  "boulevard suchet",
  "boulevard murat",
  "boulevard lefebvre",
  "boulevard brune",
  "boulevard jourdan",
  "boulevard kellermann",
  "boulevard masséna",
  "boulevard poniatowski",
  "boulevard soult",
  "boulevard davout",
  "boulevard mortier",
  "boulevard sérurier",
  "boulevard macdonald",
  "boulevard ney",
  "boulevard ornano",
  "boulevard des batignolles",
  "boulevard de courcelles",
  "boulevard pereire",
  "boulevard berthier",
  "boulevard bessières",
  "boulevard de la chapelle",
  "boulevard de la villette",
  "boulevard de belleville",
  "boulevard de ménilmontant",
  "boulevard de charonne",
  "boulevard de picpus",
  "boulevard de reuilly",
  "boulevard de bercy",
  "boulevard de l'hôpital",
  "boulevard auguste blanqui",
  "boulevard arago",
  "boulevard saint-jacques",
  "boulevard port-royal",
  "boulevard du palais",
  "boulevard henri iv",
  "boulevard bourdon",
  "boulevard morland",
  "boulevard diderot",
  "boulevard de la bastille",
  "boulevard des italiens",
  "boulevard montmartre",
  "boulevard poissonnière",
  "boulevard bonne-nouvelle",
  "boulevard saint-denis",
  "boulevard saint-martin",
  "boulevard du temple",
  "boulevard des filles-du-calvaire",
  "boulevard de grenelle",
  "boulevard garibaldi",
  "boulevard pasteur",
  "boulevard brune",
  "rue la fayette",
  "rue du quatre-septembre",
  "rue du louvre",
  "rue de turbigo",
  "rue beaubourg",
  "rue du renard",
  "rue saint-martin",
  "rue saint-denis",
  "rue du faubourg saint-denis",
  "rue du faubourg saint-martin",
  "rue du faubourg poissonnière",
  "rue la boétie",
  "rue de courcelles",
  "rue de prony",
  "rue cardinet",
  "rue de rome",
  "rue d'amsterdam",
  "rue de clichy",
  "rue caulaincourt",
  "rue ordener",
  "rue marcadet",
  "rue championnet",
  "rue damrémont",
  "rue de crimée",
  "rue de l'ourcq",
  "rue de meaux",
  "rue manin",
  "rue haxo",
  "rue de bagnolet",
  "rue d'avron",
  "rue de montreuil",
  "rue du faubourg saint-antoine",
  "rue de lyon",
  "rue de charenton",
  "rue de reuilly",
  "rue claude decaen",
  "rue de picpus",
  "rue de la convention",
  "rue lecourbe",
  "rue cambronne",
  "rue saint-dominique",
  "rue de grenelle",
  "rue de sèvres",
  "rue du cherche-midi",
  "rue d'assas",
  "rue gay-lussac",
  "rue soufflot",
  "rue monge",
  "rue claude bernard",
  "rue des écoles",
  "rue saint-jacques",
  "rue de la santé",
  "rue bobillot",
  "rue nationale",
  "rue de patay",
  "rue du chevaleret",
  "rue jeanne d'arc",
  "quai de la rapée",
  "quai d'austerlitz",
  "quai de la gare",
  "quai françois mauriac",
  "quai de bercy",
  "quai de seine",
  "quai de loire",
]);

const MONUMENT_NAMES = new Set([
  "tour eiffel",
  "musée du louvre",
  "cathédrale notre-dame de paris",
  "arc de triomphe",
  "sacré-cœur",
  "panthéon",
  "opéra garnier",
  "hôtel de ville",
  "place de la concorde",
  "place des vosges",
  "jardin du luxembourg",
  "jardin des tuileries",
  "centre pompidou",
  "musée d'orsay",
  "invalides",
  "grand palais",
  "petit palais",
  "palais de chaillot",
  "palais royal",
  "conciergerie",
  "sainte-chapelle",
  "cimetière du père-lachaise",
  "tour montparnasse",
  "bibliothèque nationale de france",
  "institut du monde arabe",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "canal saint-martin",
  "moulin rouge",
  "galeries lafayette",
  "la samaritaine",
  "pont alexandre iii",
  "pont neuf",
  "pont des arts",
  "pont de bir-hakeim",
  "parc des buttes-chaumont",
  "parc monceau",
  "bois de boulogne",
  "bois de vincennes",
]);

const ARRONDISSEMENT_PAR_QUARTIER = Object.fromEntries(
  Array.from({ length: 20 }, (_, index) => {
    const number = index + 1;
    const label = number === 1 ? "1er arrondissement" : `${number}e arrondissement`;
    return [label, number === 1 ? "1er" : `${number}e`];
  }),
);

if (typeof module !== "undefined" && module.exports) {
  module.exports = { FAMOUS_STREET_NAMES, MAIN_STREET_NAMES, MONUMENT_NAMES, ARRONDISSEMENT_PAR_QUARTIER };
}
