const FAMOUS_STREET_NAMES = new Set([
  "avenue des champs-élysées",
  "rue de rivoli",
  "boulevard saint-germain",
  "boulevard haussmann",
  "avenue montaigne",
  "avenue george v",
  "avenue de l'opéra",
  "rue saint-honoré",
  "rue du faubourg saint-honoré",
  "place vendôme",
  "place de la concorde",
  "place charles de gaulle",
  "avenue victor hugo",
  "avenue foch",
  "avenue kléber",
  "avenue de la grande armée",
  "boulevard de clichy",
  "boulevard de rochechouart",
  "rue de la paix",
  "rue de rennes",
  "rue de vaugirard",
  "rue mouffetard",
  "rue des rosiers",
  "rue de la huchette",
  "rue oberkampf",
  "rue de charonne",
  "rue saint-antoine",
  "rue du temple",
  "rue vieille du temple",
  "rue des martyrs",
  "rue lepic",
  "rue d'aboukir",
  "rue montorgueil",
  "rue étienne marcel",
  "rue réaumur",
  "boulevard de sébastopol",
  "boulevard saint-michel",
  "boulevard du montparnasse",
  "boulevard raspail",
  "boulevard voltaire",
  "boulevard beaumarchais",
  "boulevard richard-lenoir",
  "boulevard magenta",
  "boulevard barbès",
  "boulevard malesherbes",
  "avenue de wagram",
  "avenue de suffren",
  "avenue de la motte-picquet",
  "avenue de la bourdonnais",
  "avenue de tourville",
  "avenue de breteuil",
  "avenue du maine",
  "avenue d'italie",
  "avenue des gobelins",
  "avenue de choisy",
  "avenue de clichy",
  "avenue de saint-ouen",
  "avenue jean jaurès",
  "avenue simon bolivar",
  "avenue parmentier",
  "avenue ledru-rollin",
  "avenue daumesnil",
  "cours de vincennes",
  "rue de belleville",
  "rue des pyrénées",
  "rue d'alésia",
  "rue de tolbiac",
  "rue de bercy",
  "quai de la mégisserie",
  "quai des grands augustins",
  "quai de conti",
  "quai d'orsay",
  "quai branly",
  "quai de jemmapes",
  "quai de valmy",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "place d'italie",
  "place des vosges",
  "place du tertre",
]);

const MAIN_STREET_NAMES = new Set([
  ...FAMOUS_STREET_NAMES,
  "avenue de flandre",
  "avenue corentin cariou",
  "avenue de la porte de la villette",
  "avenue de la porte de clichy",
  "avenue de la porte d'asnières",
  "avenue de la porte maillot",
  "avenue de la porte d'auteuil",
  "avenue de versailles",
  "avenue émile zola",
  "avenue félix faure",
  "avenue du général leclerc",
  "avenue denfert-rochereau",
  "avenue des ternes",
  "avenue mac-mahon",
  "avenue niel",
  "avenue de friedland",
  "avenue hoche",
  "avenue marceau",
  "avenue pierre ier de serbie",
  "avenue bosquet",
  "avenue rapp",
  "avenue lowendal",
  "avenue de ségur",
  "avenue de villiers",
  "avenue de saint-mandé",
  "avenue de la république",
  "avenue gambetta",
  "avenue philippe auguste",
  "avenue de clichy",
  "avenue trudaine",
  "avenue secrétan",
  "avenue mathurin moreau",
  "avenue de laumière",
  "avenue de france",
  "avenue pierre mendès france",
  "avenue des champs-élysées",
  "boulevard périphérique",
  "boulevard lannes",
  "boulevard suchet",
  "boulevard murat",
  "boulevard lefebvre",
  "boulevard brune",
  "boulevard jourdan",
  "boulevard kellermann",
  "boulevard masséna",
  "boulevard poniatowski",
  "boulevard soult",
  "boulevard davout",
  "boulevard mortier",
  "boulevard sérurier",
  "boulevard macdonald",
  "boulevard ney",
  "boulevard ornano",
  "boulevard des batignolles",
  "boulevard de courcelles",
  "boulevard pereire",
  "boulevard berthier",
  "boulevard bessières",
  "boulevard de la chapelle",
  "boulevard de la villette",
  "boulevard de belleville",
  "boulevard de ménilmontant",
  "boulevard de charonne",
  "boulevard de picpus",
  "boulevard de reuilly",
  "boulevard de bercy",
  "boulevard de l'hôpital",
  "boulevard auguste blanqui",
  "boulevard arago",
  "boulevard saint-jacques",
  "boulevard port-royal",
  "boulevard du palais",
  "boulevard henri iv",
  "boulevard bourdon",
  "boulevard morland",
  "boulevard diderot",
  "boulevard de la bastille",
  "boulevard des italiens",
  "boulevard montmartre",
  "boulevard poissonnière",
  "boulevard bonne-nouvelle",
  "boulevard saint-denis",
  "boulevard saint-martin",
  "boulevard du temple",
  "boulevard des filles-du-calvaire",
  "boulevard de grenelle",
  "boulevard garibaldi",
  "boulevard pasteur",
  "boulevard brune",
  "rue la fayette",
  "rue du quatre-septembre",
  "rue du louvre",
  "rue de turbigo",
  "rue beaubourg",
  "rue du renard",
  "rue saint-martin",
  "rue saint-denis",
  "rue du faubourg saint-denis",
  "rue du faubourg saint-martin",
  "rue du faubourg poissonnière",
  "rue la boétie",
  "rue de courcelles",
  "rue de prony",
  "rue cardinet",
  "rue de rome",
  "rue d'amsterdam",
  "rue de clichy",
  "rue caulaincourt",
  "rue ordener",
  "rue marcadet",
  "rue championnet",
  "rue damrémont",
  "rue de crimée",
  "rue de l'ourcq",
  "rue de meaux",
  "rue manin",
  "rue haxo",
  "rue de bagnolet",
  "rue d'avron",
  "rue de montreuil",
  "rue du faubourg saint-antoine",
  "rue de lyon",
  "rue de charenton",
  "rue de reuilly",
  "rue claude decaen",
  "rue de picpus",
  "rue de la convention",
  "rue lecourbe",
  "rue cambronne",
  "rue saint-dominique",
  "rue de grenelle",
  "rue de sèvres",
  "rue du cherche-midi",
  "rue d'assas",
  "rue gay-lussac",
  "rue soufflot",
  "rue monge",
  "rue claude bernard",
  "rue des écoles",
  "rue saint-jacques",
  "rue de la santé",
  "rue bobillot",
  "rue nationale",
  "rue de patay",
  "rue du chevaleret",
  "rue jeanne d'arc",
  "quai de la rapée",
  "quai d'austerlitz",
  "quai de la gare",
  "quai françois mauriac",
  "quai de bercy",
  "quai de seine",
  "quai de loire",
]);

const MONUMENT_NAMES = new Set([
  "tour eiffel",
  "musée du louvre",
  "cathédrale notre-dame de paris",
  "arc de triomphe",
  "sacré-cœur",
  "panthéon",
  "opéra garnier",
  "hôtel de ville",
  "place de la concorde",
  "place des vosges",
  "jardin du luxembourg",
  "jardin des tuileries",
  "centre pompidou",
  "musée d'orsay",
  "invalides",
  "grand palais",
  "petit palais",
  "palais de chaillot",
  "palais royal",
  "conciergerie",
  "sainte-chapelle",
  "cimetière du père-lachaise",
  "tour montparnasse",
  "bibliothèque nationale de france",
  "institut du monde arabe",
  "place de la bastille",
  "place de la république",
  "place de la nation",
  "canal saint-martin",
  "moulin rouge",
  "galeries lafayette",
  "la samaritaine",
  "pont alexandre iii",
  "pont neuf",
  "pont des arts",
  "pont de bir-hakeim",
  "parc des buttes-chaumont",
  "parc monceau",
  "bois de boulogne",
  "bois de vincennes",
]);

const ARRONDISSEMENT_PAR_QUARTIER = Object.fromEntries(
  Array.from({ length: 20 }, (_, index) => {
    const number = index + 1;
    const label = number === 1 ? "1er arrondissement" : `${number}e arrondissement`;
    return [label, number === 1 ? "1er" : `${number}e`];
  }),
);

if (typeof module !== "undefined" && module.exports) {
  module.exports = { FAMOUS_STREET_NAMES, MAIN_STREET_NAMES, MONUMENT_NAMES, ARRONDISSEMENT_PAR_QUARTIER };
}
